### ISSUE TITLE
Jagged lines are created when using touch on a mobile device

### ISSUE THREAD

**Issue by jnm2** [jnm2/epic#5]
I don't remember this being a problem when I tried https://jsfiddle.net/jnm236/d67kxw1q/1/show on my Android.

![Screenshot_20201120-010309_Brave](https://user-images.githubusercontent.com/8040367/99765153-73d58480-2acc-11eb-8c58-e8a20123be0d.jpg)

**Comment by Daynvheur** [comment]
I don't see any troubles on iPad (Chrome): https://jsfiddle.net/Dinosaure/cuya293j/1/show ,

**Comment by Daynvheur** [comment]
Give a check at 23f446a / https://jsfiddle.net/Dinosaure/cuya293j/16/show, the jagged lines came from touch events conflicting with pointer events.

**Comment by jnm2** [comment]
Confirmed! Wow, you're fast!
